### ISSUE TITLE
Haiku OS support

### ISSUE THREAD

**Issue by filip2cz** [ur-fault/TMaze#103]
- [ ] [Update dependencies to support Haiku OS](https://github.com/ur-fault/TMaze/issues/101)
- [ ] Fix freezing on Haiku OS
- [ ] Packaging

**Comment by ur-fault** [comment]
Simple updating the dep makes it compile and run successfully (at least without `updates` feature), but it hangs on every terminal event. I tried running their official example [interactive-demo](https://github.com/crossterm-rs/crossterm/tree/master/examples/interactive-demo), but it had the same issue, so it's not our fault.

**Comment by ur-fault** [comment]
So until they fix it, I will close this for now.
